name: flutter_inapp_notifications
description: A simple Flutter package to generate instant customizable in-app notifications.
version: 1.0.1
repository: https://github.com/FlutteristDev/flutter_inapp_notifications

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0